accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accountapp.views import hello_world, test, AccountCreateView, AccountDetailView, AccountUpdateView, trafficmap, trmap

#"127.0.0.1:8000/account/hello_world"  <-- 이렇게 들어와야 하는데
#app_name 을 만들어 줌으로써  접급이 용이해짐... 나중에 ..

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name = 'hello_world'),
    #path('', hello_world, name = 'hello_world'),

    path('test/', test, name = 'test'),
    path('trafficmap/', trafficmap, name = 'trafficmap'),
    path('trmap/', trmap, name='trmap'),


    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), #template 설정을 해줘야 함
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),  #view.py에서 class를 사용한 경우 .as_view()를 붙여주라
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls'))
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView

from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld



def hello_world(request):
    if request.method == "POST":
        temp = request.POST.get('hello_world_input')
        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


# 내가 걍 이해하기 위해서 만들어본 것
def test(request):
    return render(request, 'test.html')

def trafficmap(request):
    return render(request, 'trafficmap.html')

def trmap(request):
    return render(request, 'accountapp/trmap.html')


# 수업내역

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px;margin: 4rem auto">
        <div class="mb-4">
            <h4>
                SignUp
            </h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
<!--            {{ form }}-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; margin: 4rem, auto; ">
        <p>
            {{ target_user.date_joined}}
        </p>
        <h2 style="font-family: 'NanumSquareB' ">
            {{ target_user.username }}
    </h2>
{% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
        {% endif %}

    </div>
</div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

<!-- extend를 사용하기 위해서 block 구문을 사용-->
{% block content %}

     <div style="text-align:center;border-radius: 1rem; margin: 2rem;">
         <h1 style="font-family: 'Gugi', cursive;"> hello world list
         </h1>
         <h1 style="font-size:0.4rem;"> accountapp/templates/accountapp/hello_world.html 불러왔음
         </h1>

<!--  post를 사용하기 위해서 form 과 input 구문을 사용함
      post 사용하기 위해서 django 에서는 토큰을 사용해야 함
      -->
     <form action="/account/hello_world/" method="post">
         {% csrf_token %}
         <div>
            <input type="text" name="hello_world_input">
         </div>

         <input type="submit" class="btn btn-primary" value="POST">
     </form>
         {% if hello_world_list %}
                {% for hello_world in hello_world_list %}
                 <h4>
                    {{ hello_world.text }}
                 </h4>
                {% endfor %}
         {% endif %}
     </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px;margin: 4rem auto">
        <div>
            <h4>Login(로그인)</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
<!--                {{ form }}-->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/trmap.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    {% include 'trafficmap.html' %}

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
 <div style="text-align: center; max-width:500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>
                Chang Info
            </h4>
        </div>
        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family:'NanumSquareL';">
    {% include 'header.html' %}
    <!-- 이걸 3개 만들어서 헤드-바디-푸터 영역을 나누는걸 설명했음  <div style="height: 20rem; background-color: #38df81; border-radius: 1rem; margin: 2rem;"></div>-->
<hr>   <!-- 구분 선 삽입-->
    <!-- extend를 사용하기 위해서 block 구문을 사용-->
    {% block content %}
    {% endblock %}
<hr>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class ="pragmatic_footer">
    <div class ="pragmatic_footer_button">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style ="margin-top: 1rem;">
        <h6 class="pragmatic_logo">Pragmatic web by JYW</h6>
    </div>
</div>

templates/head.html
{% load static %}


<head>
    <meta charset="UTF-8">
    <title>Pragmatic_jyw</title>
<!--bootstrap link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

<!-- google font   -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gugi&display=swap" rel="stylesheet">

    
<!--default css link    -->
    <link rel="stylesheet" type="text/css", href="{% static 'base.css' %}">
    <style>
    @font-face {
        font-family: 'NanumSquareR';
        src: local('NanumSquareR'),
        url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareEB';
        src: local('NanumSquareEB'),
        url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
    }
    @font-face {
    font-family: 'NanumSquareB';
    src: local('NanumSquareB'),
    url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
    }
    @font-face {
        font-family: 'NanumSquareL';
        src: local('NanumSquareL'),
        url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
    }
    </style>
</head>

templates/header.html
<!-- style="height: 10rem; background-color: #38df81; border-radius: 1rem; margin: 2rem;"> -->
<div class="pragmatic_header">
    <div class="pragmatic_logo">
        <h1 style="font-size:4rem;">Pragmatic web course</h1>
    </div>
    <div>
                <a href="{% url 'accountapp:hello_world' %}">
                    <span>Home</span>
                </a>
<!--            <span>nav2</span>-->
<!--            <span>nav3</span>-->
                <a class = "menu-trigger" href="{% url 'accountapp:trmap' %}">
                    <span>Traffic map</span>
                </a>
            {% if not user.is_authenticated %}
                <a class = "menu-trigger" href="{% url 'accountapp:login' %}?next={{request.path}}">
                    <span>login</span>
                </a>


        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>

        <a href="{% url 'accountapp:logout' %}?next={{request.path}}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
</div>

templates/test.html
<!doctype html>
<html lang="ko"> <head> <!-- 메타 태그 -->
	<meta charset="utf-8">
	<meta name="viewport"content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS CDN -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<title>my test </title>
	</head>
	<body>
		<h1>버튼 태그</h1>
		<input type="button" value='버튼'name="JYW" onclick="alert('hi')">
		<input type="text" name="JYW1" onchange="alert('changed')">
		<input type="text" name="JYW2" onkeydown="alert('key down!')">

		<!-- Bootstrap JS CDN -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
	</body>
	</html>